// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/hapmap/hapmap-reader.js', ['hapmap.HapmapReader'], ['goog.math.Long', 'goog.string.format', 'hapmap.models.LDItem'], false);
goog.addDependency('../../../../src/hapmap/hapmap.js', ['hapmap'], ['hapmap.HapmapReader'], false);
goog.addDependency('../../../../src/hapmap/models/ld-item.js', ['hapmap.models.LDItem'], [], false);
